#cloud-config
package_update: true
users:
 - default
 - name: jenkins
runcmd:
 - apt install -y openjdk-11-jdk
 - apt install -y maven
 - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
 - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
 - apt update
 - apt install -y jenkins
